name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ github.event.workflow_run.head_commit.id }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      - run: ls -a developers
#          unzip build-${{ github.event.workflow_run.head_commit.id }}.zip
          
#          cd build-${{ github.event.pull_request.head.sha }}
# Deploy the artifact to Clever Cloud
# Use CC_WEBROOT or git init in the artifact directory?
# Tests: ls -a in the runner