name: Deploy

on:
  pull_request_target:
    types: [opened, closed, synchronize, reopened]
    branches: [ main ]

jobs:
  review-app:
    runs-on: ubuntu-latest
    if: 
    permissions:
      actions: read
      contents: write
    steps:
      - name: Wait for build to succeed
        uses: yandzee/wait-action@main
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          # Required param
          head-sha: ${{ github.event.pull_request.head.sha }}
          poll-delay: 10s
          # Comma separated paths to workflow files
          workflows: .github/workflows/build.yml
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      - run: |
          ls -a
      - name: Deploy on CC
        uses: CleverCloud/clever-cloud-review-app@optional-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.ORGA_ID }}
          GH_CC_WEBROOT: '/public'
        with:
          type: static-apache
          comment: false
# Deploy the artifact to Clever Cloud
# Use CC_WEBROOT or git init in the artifact directory?
# Tests: ls -a in the runner